name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: 3.8
        auto-update-conda: true
        activate-environment: myenv
        environment-file: environment.yml

    - name: Install additional dependencies
      run: |
        conda install -n myenv flake8 pytest

    - name: Check syntax (compilation)
      run: |
        conda run -n myenv python -m py_compile src/fiesta.py
        conda run -n myenv python -m py_compile src/subsecuencias.py
        if [ $? -eq 0 ]; then echo "fiesta: correcto"; echo "subsecuencias: correcto"; else echo "Errores en la compilación"; fi

        - name: Lint with flake8 (non-blocking, filtered)
        continue-on-error: true
        run: |
        echo "Ejecutando flake8..."
        ERRORS=$(conda run -n myenv flake8 src/ tests/ \
          --ignore=W391,W292,F401,E302,E712,E501,E261,E262,E305,E301,E114,E117,W291,W293,E225 \
          || true)

        echo "$ERRORS"

        check_passed() {
          FILE=$1
          if echo "$ERRORS" | grep -q "$FILE"; then
            echo "$FILE: errores encontrados"
          else
            echo "$FILE: correcto"
          fi
        }

        check_passed "src/fiesta.py"
        check_passed "src/subsecuencias.py"
        check_passed "tests/test_fiesta.py"
        check_passed "tests/test_subsecuencias.py"


    - name: Run tests with pytest
      env:
        PYTHONPATH: src
      run: |
        conda run -n myenv pytest tests/
        if [ $? -eq 0 ]; then echo "fiesta: correcto"; echo "subsecuencias: correcto"; echo "test_fiesta: correcto"; echo "test_subsecuencias: correcto"; else echo "Errores en las pruebas"; fi








